from itertools import islice
import argparse as ap
import glob
parser = ap.ArgumentParser()

parser.add_argument('expression_dir', help = 'file path of directory containing expression files generated by Salmon_Parser.R')
parser.add_argument('associated_names', help = 'the file E-GEUV-1.sdrf.txt containing all the name associations') 
args = parser.parse_args()

#would be better to generate this names dictionary once and reuse it for all files in a loop
names_dict = {}
with open(args.associated_names, 'r', encoding = 'utf-8') as names:
	next(names)
	for line in names:
		fields = line.strip('\n').split('\t')
		names_dict[fields[27]] = fields[0]


files = glob.glob(args.expression_dir + "expression_sal_chr*")
for file in files:
  with open(file, 'rt', encoding='utf-8') as target:
	  header = target.readline().strip('\n').split()
	  new_header = ['gene_id']
	  for colname in header:
		  if colname in names_dict:
			  new_header.append(names_dict[colname])
	  with open("renamed_" + file, 'wt', encoding='utf-8') as out:
		  out.write(" ".join(new_header) + "\n") 
		  #next(target)
		  for line in file:
			  out.write(line)
      
