#!/bin/bash

AnnotationFileDefault=~/Data/GenCode/gencode.v28.annotation.gtf
BamDirectoryDefault=~/testruns/StarAlignments
FastqDirDefault=~/Data/gEUVADIS_RNASeq
FastQCDirDefault=~/testruns/
GenomeFileDefault=~/Data/GenCode/GRCh38.primary_assembly.genome.fa
MeanThresholdDefault=0.1
QuantDirectoryDefault=~/testruns/SalQuant/
SampleListDefault=~/sample_list.txt
SampleNumberDefault=10
SNPGenotypeFileDefault=~/testSNPgenotype.txt
SNPLocationFileDefault=~/testSNPlocation.txt
SNPOutDefault=~/Data/SNPdata
TranscriptFileDefault=~/Data/GenCode/gencode.v28.transcripts.fa
TagDefault=tag
VarThresholdDefault=0.1
VCFFileDefault=~/Data/SNPdata/chr1-22.vcf.gz

while :
do
    case "$1" in
      -a | --annotationfile) #path to annotation file
	       	AnnotationFile="$2"
	       	shift 2
	       	;;
      -b | --bamdirectory) #name for directory containing bamfiles. If doesn't exist and running STAR, will create directory
   	     	BamDirectory="$2"
        	shift 2
   	  	;;
      -f | --fastqdirectory) #directory containing the fastq files to be processed
   	     	FastqDir="$2"
   	     	shift 2
   	    	;;
      -fqc | --fastqcdirectory) #directory where you'd like to write Summary_FastQC files
	     FastQCDir="$2"
		shift 2
		;;
      -g | --genomefile) #path to the genome file
   	     GenomeFile="$2"
		shift 2
		;;
      -id | --indexdirectory) #directory containing STAR index. Will create index here if running indexing.
         	IndexDirectory="$2"
         	shift 2
         	;;
      -l | --libtype) #Library type (paired end vs sigle etc.)
         	LibraryType="$2"
         	shift 2
         	;;
      -m | --meanthreshold)
		MeanThreshold="$2"
		shift 2
		;;
      -n | --samplenumber)
		SampleNumber="$2"
		shift 2
		;;
      -q | --quantdirectory) #directory where quantification results will be written. If doesn't exist will create directory.
         	QuantDirectory="$2"
         	shift 2
      	 	;;
      -ri | --runindex) #accepts T or F - would you like to run Indexing? By default F
         	RunIndex="$2"
         	shift 2
         	;;
      -s | --samplelist) #list of Fastq samples you'd like to process in the Fastqdir
         	SampleList="$2"
         	shift 2
         	;;
      -sg | --SNPgenotype) #Path to file containing your SNP genotypes for all samples processed
       	 	SNPGenotypeFile="$2"
         	shift 2
         	;;
      -sl | --SNPgenotype) #Path to file containing SNP Locations for all samples processed
         	SNPGenotypeFile="$2"
         	shift 2
         	;;
      -so | --SNPout)
         	SNPout="$2"
         	shift 2
         	;;
      -t | --transciptfile) #Path to transcript file
       	 	TranscriptFile="$2"
         	shift 2
         	;;
      -tag)
         	Tag="$2"
         	shift 2
         	;;
      -v | --variancethreshold)
		VarThreshold="$2"
		shift 2
		;;
      -VCF)
		VCFFile="$2"
		shift 2
		;;
      -*) #unknown 
	 	echo "Error: Unknown option: $1" >&2
	 	exit 1
	  	;;
      *)  # No more options
		shift
	  	break
	  	;;
     esac
done

#list samples three options -i fastqdir -o write directory -s sample size

RNA-Seq_Pipeline_Project/codes/filtering/list_samples -i "${FastqDir:=FastqDirDefault}" -o "${SampleList:=SampleListDefault}" -s "${SampleNumber:=SampleNumberDefault}" -SNP "${SNPGenotypeFile:=SNPGenotypeFileDefault}"
echo "Beginning FastQC"
RNA-Seq_Pipeline_Project/codes/fastqc_loop -f "${FastqDir:=$FastqDirDefault}" -o "${FastQCDir:=$FastQCDirDefault}" -s "${SampleList:=$SampleListDefault}"
echo "Finished FastQC"
echo "Beginning Alignment"
RNA-Seq_Pipeline_Project/codes/star_loop -a "${AnnotationFile:=$AnnotationFileDefault}" -g "${GenomeFile:=$GenomeFileDefault}" -i "${FastqDir:=$FastqDirDefault}" -id "${IndexDirectory:=}" -o "${BamDirectory:=$BamDirectoryDefault}" -ri "${RunIndex:=}" -s "${SampleList:=$SampleListDefault}" -t "${Threads:=}" -VCF "${VCFFile:=$VCFFileDefault}"
echo "Finished Alignment"
echo "Beginning Quantification"
RNA-Seq_Pipeline_Project/codes/salmon_loop -a "${AnnotationFile:=$AnnotationFileDefault}" -i "${BamDirectory:=$BamDirectoryDefault}" -l "${LibraryType:=}" -o "${QuantDirectory:=$QuantDirectoryDefault}" -s "${SampleList:=$SampleListDefault}" -t "${TranscriptFile:=$TranscriptFileDefault}"
echo "Finished Quantification"
echo "Parsing & Filterng"
Rscript RNA-Seq_Pipeline_Project/codes/filtering/Salmon_parser.R -a "${AnnotationFile:=$AnnotationFileDefault}" -q "${QuantDirectory:=$QuantDirectoryDefault}" -o "${QuantDirectory:=}"/expression_location -m "${MeanThreshold:=$MeanThresholdDefault}" -v "${VarThreshold:=$VarThresholdDefault}"
Rscript ~/RNA-Seq_Pipeline_Project/codes/filtering/SNP_subset.R -s "${SampleList:=$SampleListDefault}" -sg "${SNPGenotypeFile:=$SNPGenotypeFileDefault}" -sl "${SNPLocationFile:=$SNPLocationFileDefault}" -t "${Tag:=$TagDefault}" -o "${SNPout:=$SNPOutDefault}"
echo "Finished parsing & Filtering"
echo "beginning eqtl analysis on 22 autosomes"
for i in $( seq 1 22 )
do
      Rscript ~/RNA-Seq_Pipeline_Project/codes/MatrixEQTL.R -sg "${SNPout}"/"${Tag}SNPgenotype.txt" -sl "${SNPout}"/"${Tag}SNPlocation.txt" -ge "${QuantDirectory:=$QuantDirectoryDefault}"/expression_location/"expression_sal_chr${i}" -gl "${QuantDirectory:=$QuantDirectoryDefault}"/expression_location/"location_sal_chr${i}" -t "chr${i}"
done
