#!/bin/bash

Rscript ./sample_filtering.R --samplelist --snpgenotype --outputdir
python3 dosage_extract.py --VCF --maf --r2 --outputdir --tag
./star_loop -g $PATH/$TO/genome.fa -s $PATH/$TO/sample_list.txt --inputdirectory $PATH/$TO/fastqdirectory/  -a $PATH/$TO/annotations.gencode.gtf --runindex
./salmon_loop -t $PATH/$TO/transcriptome.fa -b $PATH/$TO/BAMdirectory/ -a $PATH/$TO/annotations.gencode.gtf -s $PATH/$TO/sample_list.txt
#Rscript Salmon_parser.R
Rscript SNP_subset.R --samplelist Path/to/sample_list.txt --snpgenotype Path/to/SNPGenotypes.txt.gz --snplocation Path/to/SNPLoc.txt.gz --outputdir out --tag example_label
for i in $(seq 1 22)
do
     Rscript MatrixEQTL.R -sg PATH/TO/snp_genotype -sl PATH/TO/snp_location -ge PATH/TO/gene_expression_chr"{$i}" -gl PATH/TO/gene_location_chr"{$i}" 
done
