#!/bin/bash

BootDefault=0
SampDefault=10

while :
do
    case "$1" in
      -b | --bootstrap) #number of desired bootstraps. Default is 0.
	  Bootstrap="$2"
	  shift 2
	  ;;
      -i | --inputdirectory) #directory containing the fastq files to be processed
	  FastqDir="$2"  
	  shift 2
	  ;;
      -s | --samplenumber) #number of samples you wish to process. Assumes samples are paired fastq files. Default is 10.
	  SampNum="$2"
	  shift 2
	  ;;
      -*)
	  echo "Error: Unknown option: $1" >&2
	  exit 1
	  ;;
      *)  # No more options
	  shift
	  break
	  ;;
     esac
done

if [ -z "$FastqDir" ]
then
	echo "Warning: Fastq directory not set"
	echo "Exiting" 
	exit 1
fi

if [ -z "$Bootstrap" ] 
then
 	echo "Using default bootstrap of 0"
	Bootstrap="$BootDefault"
fi

if [ -z "$SampNum" ] 
then
  	echo "using default sample size of 10"
	SampNum="$SampDefault"
fi
#	  break
#	  ;;
#    esac
#done

#user input should go around here
#can have the initial input be a flag

if [ -e fastq_list_Kal.txt ] #remove any file with this name at the start
then
	rm fastq_list_Kal.txt
fi 

for file in `ls "${FastqDir}"*fastq.gz | cut -f 6 -d '/' | cut -f 1 -d '_' | uniq | head -n "${SampNum}"` #generate fastq list from scratch
do
	echo "$file" >> fastq_list.txt #write just the primary tag
done

#cat fastq_list.txt | while read fastq #now iterate through the list of fastq files
#if [ -e "$fastq" ]
#then
#	rm -r "$fastq" #if a directory with the fastq name already exists rm it to avoid colisions
#fi
#do 
#	/usr/local/bin/anaconda2/bin/kallisto quant -i ~/transcripts.idx -o ./"${fastq}" -b "${Bootstrap}" "${FastqDir}""${fastq}"* #run kallisto quantification on each paired file 
#	/usr/local/bin/anaconda3/bin/python3 ~/scripts/reads_per_gene_Kallisto.py ~/"${fastq}"/abundanve.tsv ~/"${fastq}"/Gene_abundance.tsv

#done
