#!/bin/bash

FastqDir=$1

if [ -e fastq_list_star.txt ] #remove any files with this name to start with
then
	rm fastq_list_star.txt 
fi 
for file in `ls "${FastqDir}"*fastq.gz | cut -f 6 -d '/' | cut -f 1 -d '_' | uniq | head -n 10` #generate fastq list from scratch
do
	echo $file >> fastq_list_star.txt
done

#STAR indexing will go here
#rsem reference file generation will go here

cat fastq_list_star.txt | while read fastq #iterate through the list
if [ -e "${fastq}_star" ]
then
	rm -r ~/test_runs/"${fastq}_star" #remove any folders that might have this name
fi
do
	mkdir ~/test_runs/"${fastq}_star" #make the directory
	cd ~/test_runs/"${fastq}_star" #go to that directory
	STAR --genomeDir ~/StarTest/ --sjdbGTFfile ~/DATA/GenCode/gencode.v28.annotations.gtf --readFilesIn "${FastqDir}""${fastq}"* --readFilesCommand zcat --quantMode TranscriptomeSAM GeneCounts --outSAMtype BAM Unsorted SortedByCoordinate
done
