#!/bin/bash

FastqDir=$1 #needs directory containing the fastq files as input

if [ -e fastq_list_0.txt ] #remove any file with this name at the start
then
	rm fastq_list_0.txt
fi 
for file in `ls ${FastqDir}*fastq.gz | cut -f 6 -d '/' | cut -f 1 -d '_' | uniq | head` #generate fastq list from scratch
do
	echo $file >> fastq_list_0.txt #write just the primary tag
done

#user input should go around here
#has an index file been created yet?
#or we can have the initial input be a flag somehow?

cat fastq_list_0.txt | while read fastq #now iterate through the list of fastq files
if [ -e ${fastq}_0 ]
then
	rm -r ${fastq}_0 #if a directory with the fastq name already exists rm it to avoid colisions
fi
do 
	/usr/local/bin/anaconda2/bin/kallisto quant -i ~/transcripts.idx --genomebam --gtf ~/DATA/GenCode/gencode.v28.annotation.gtf -o ./${fastq}_0 -b 0 ${FastqDir}${fastq}* #run kallisto quantification on each paired file 
	/usr/local/bin/anaconda3/bin/python3 ~/scripts/reads_per_gene_Kallisto.py ~/${fastq}_0/abundance.tsv ~/${fastq}_0/Gene_abundance.tsv
done
