#!/bin/bash

FastqDir=$1 #needs directory containing the fastq files as input
BootDefault=100
SampDefault=10

if [ -n "$2" ]
then
	Bootstrap=$2
else
	Bootstrap=$BootDefault
fi

if [ -n "$3" ]
then
	SampNum=$3
else
	SampNum=$SampDefault
fi

#user input should go around here
#has an index file been created yet?
#or we can have the initial input be a flag somehow?

if [ -e fastq_list.txt ] #remove any file with this name at the start
then
	rm fastq_list.txt
fi 
for file in `ls "${FastqDir}"*fastq.gz | cut -f 6 -d '/' | cut -f 1 -d '_' | uniq | head -n "${SampNum}"` #generate fastq list from scratch
do
	echo "$file" >> fastq_list.txt #write just the primary tag
done

cat fastq_list.txt | while read fastq #now iterate through the list of fastq files
if [ -e "$fastq" ]
then
	rm -r "$fastq" #if a directory with the fastq name already exists rm it to avoid colisions
fi
do 
	/usr/local/bin/anaconda2/bin/kallisto quant -i ~/transcripts.idx -o ./"${fastq}" -b "${Bootstrap}" "${FastqDir}""${fastq}"* #run kallisto quantification on each paired file 
	/usr/local/bin/anaconda3/bin/python3 ~/scripts/reads_per_gene_Kallisto.py ~/"${fastq}"/abundanve.tsv ~/"${fastq}"/Gene_abundance.tsv

done
