#!/bin/bash
#uncomment next line for automatic path addition
#PATH=$PATH:~/salmon-0.10.0_linux_x86_64/bin/

while :
do
    case "$1" in
     
      -o | --outputprefix) #write leafcutter clustering to this directory
      	  OutputDirectory="$2"
	  shift 2
      	  ;;
      -*) #unknown 
	  echo "Error: Unknown option: $1" >&2
	  exit 1
	  ;;
      *)  # No more options
	  shift
	  break
	  ;;
     esac
done


set -e
#should add an option for output directory
#test runs directoy is a path
cat fastq_list_star.txt | while read fastq #iterate through the list
if [ -d ./test_runs/"${fastq}_star"/"salmon_quant_${fastq}" ] #temporary fix - should be altered to output path in later runs
then
	rm -rf ~/test_runs/"${fastq}_star"/"salmon_quant_${fastq}" #remove any folders that might have this name
fi
do
	salmon quant -t ~/DATA/GenCode/gencode.v28.transcripts.fa -l A -a  ~/test_runs/"${fastq}_star"/Aligned.toTranscriptome.out.bam -o ~/test_runs/"${fastq}_star"/"salmon_quant_${fastq}" --gencode -g ~/DATA/GenCode/gencode.v28.annotation.gtf
	( head -n 1 ~/test_runs/"${fastq}_star"/"salmon_quant_${fastq}"/quant.genes.sf && tail -n +2 ~/test_runs/"${fastq}_star"/"salmon_quant_${fastq}"/quant.genes.sf | sort -k 1) > ~/test_runs/"${fastq}_star"/"salmon_quant_${fastq}"/"quant.genes.${fastq}.sorted.sf"
done
