#!/bin/bash
#uncomment next line for automatic path addition
PATH=$PATH:~/software/salmon/bin/
LibraryTypeDefault=A
MeanThresholdDefault=0.1
OutputDirectoryDefault=~/SalQuant
VarianceThresholdDefault=0.1
while :
do
    case "$1" in
      -a | --annotation) #annotation file corresponding to the genome
          AnnotationFile="$2"
	  shift 2
	  ;;
      -b | --bamdirectory) #directory containing the bam files to be processed
	  BamDirectory="$2"  
	  shift 2
	  ;;
      -f | --fastqdirectory) #directory containing the bam files to be processed
	  FastqDirectory="$2"  
	  shift 2
	  ;;
      -l | --librarytype) #directory containing the fastq files to be processed
	  LibraryType="$2"  
	  shift 2
	  ;;
      -m | --meanthreshold) #directory containing the fastq files to be processed
	  MeanThreshold="$2"  
	  shift 2
	  ;;
      -o | --outputdirectory) #directory where you'd like to send all your quantification files
          OutputDirectory="$2"
	  shift 2
	  ;;
      -s | --samplelist) 
      	  SampleList="$2"
	  shift 2
	  ;;
      -t | --transcript)
	  TranscriptFile="$2"
	  shift 2
	  ;;
      -v | --variancethreshold) #directory containing the fastq files to be processed
	  VarianceThreshold="$2"  
	  shift 2
	  ;;
      -*) #unknown 
	  echo "Error: Unknown option: $1" >&2
	  exit 1
	  ;;
      *)  # No more options
	  shift
	  break
	  ;;
     esac
done

echo "Annotation file is ${AnnotationFile:?not set}"
echo "Using transcript file ${TranscriptFile:?not set}"
echo "Using sample list ${SampleList:?not set, please provide sample list}"
echo "Writing output to ${OutputDirectory:=$OutputDirectoryDefault}"
echo "Using library type of ${LibraryType:=$LibraryTypeDefault}"
if [ -z "${BamDirectory}" ] && [ -z "${FastqDirectory}" ]
then
	echo "No target files provided. Please provide directory containing either BAM or Fastq files"
	echo "Exiting"
	exit 1
fi
if [ -n "${BamDirectory}" ] && [ ! -d "${BamDirectory}" ]
then
	echo "Bam directory does not exits. please provide a valid bam directory with -b or --bamdirectory option"
	echo "Exiting"
	exit 1
fi

if [ -n "${FastqDirectory}" ] && [ ! -d "${FastqDirectory}" ]
then
	echo "Fastq directory does not exits. please provide a valid Fastq directory with -f or --fastqdirectory option"
	echo "Exiting"
	exit 1
fi

if [ -n "${BamDirectory}" ] && [ -n "${FastqDirectory}" ]
then
	echo "Cannot handle both Fastq and Bam quantification at once. Please provide only one"
	echo "Exiting"
	exit 1
fi

if [ ! -d "${OutputDirectory}" ]
then
	mkdir "${OutputDirectory}"	
fi

if [ ! -d "${OutputDirectory}"/total_population ]
then
	mkdir "${OutputDirectory}"/total_population	
fi

if [ ! -d "${OutputDirectory}"/expression_location ]
then
	mkdir "${OutputDirectory}"/expression_location
fi


if [ -n "${BamDirectory}" ]
then
	cat "${SampleList}" | while read line #iterate through the list
	do 
		Sample=$( echo "${line}" | cut -f 1 -d$'\t' )
		if [ -d "${OutputDirectory}"/"${Sample}_salmon" ] #temporary fix - should be altered to output path in later runs
		then
			rm -rf "${OutputDirectory}"/"${Sample}_salmon" #remove any folders that might have this name
		fi
		salmon quant -t "${TranscriptFile}" -l "${LibraryType}" -a  "${BamDirectory}"/"${Sample}_star"/Aligned.toTranscriptome.out.bam -o "${OutputDirectory}"/"${Sample}_salmon" --gencode -g "${AnnotationFile}"
		( head -n 1 "${OutputDirectory}"/"${Sample}_salmon"/quant.genes.sf && tail -n +2 "${OutputDirectory}"/"${Sample}_salmon"/quant.genes.sf | sort -k 1) > "${OutputDirectory}"/"${Sample}_salmon"/"${Sample}.sorted.genes.quant.sf"
	done
fi

Rscript ../filtering/Salmon_parser.R -a "${AnnotationFile}" -q "${OutputDirectory}" -m "${MeanThreshold:=$MeanThresholdDefault}" -v "${VarianceThreshold:=$VarianceThresholdDefault}" -o ${OutputDirectory}"/total_population
