#!/bin/bash

cd ~/Data/SNPdata/
awk -F$'\t' '{print > "SNP_Location_"$2".txt"}' ~/Data/SNPdata/GEU_SNPs_location.txt
for txt in SNP_Location_chr*
do
	sed -i '1i rsid\tchr\tposition' $txt
done
echo "finished splitting location file"
Rscript ~/scripts/SNP_subset.R
